#!/usr/bin/env node
/**
 * Generates SCRIPT_INDEX.md from src/data/script.ts
 * Run: npm run script-index
 */
const fs = require("fs");
const path = require("path");

const scriptPath = path.join(__dirname, "../src/data/script.ts");
const outPath = path.join(__dirname, "../SCRIPT_INDEX.md");
const content = fs.readFileSync(scriptPath, "utf8");
const lines = content.split("\n");

const rows = [];
let currentPage = null;
let currentPageLine = null;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  const lineNum = i + 1;
  const idMatch = line.match(/id:\s*["']([^"']+)["']/);
  if (idMatch) {
    if (currentPage) {
      rows.push({ id: currentPage.id, line: currentPageLine, scene: currentPage.scene });
    }
    currentPage = { id: idMatch[1], scene: "" };
    currentPageLine = lineNum;
  }
  if (currentPage && /type:\s*["']scene["']/.test(line)) {
    const textMatch = line.match(/text:\s*["']([^"']+)["']/);
    if (textMatch && !currentPage.scene) {
      currentPage.scene = textMatch[1].replace(/^(EXT\.|INT\.)\s*/, "").substring(0, 45);
    }
  }
}
if (currentPage) {
  rows.push({ id: currentPage.id, line: currentPageLine, scene: currentPage.scene });
}

const md = `# FISH Script Page Index

Generated by \`npm run script-index\`. Regenerate after editing the script.

**Editing reference:** Use \`page-id\` + \`line N\` (1-based element index) to target edits.
Example: \`page-ade-zuri-upstream line 7\` = 7th element on that page.

| Page ID | ~Line | Scene |
|---------|-------|-------|
${rows.map((r) => `| ${r.id} | ${r.line} | ${r.scene} |`).join("\n")}
`;

fs.writeFileSync(outPath, md);
console.log(`Wrote ${outPath} (${rows.length} pages)`);
